## Практикум по Pandas
https://stepik.org/course/111629/

Прокачиваем практические навыки работы в Pandas. Рекомендовано специалистам по анализу данных. Выведи своё владение библиотекой Pandas на новый уровень!

Предполагается, что вы самостоятельно работаете с документацией и другими источниками по Pandas, а здесь практикуетесь решать задачи.

Практикум включает задачи, которые могут встретиться на собеседовании и работе. После прохождения курса вы будете уверенно владеть библиотекой Pandas.

Желаем успехов в прохождении курса и освоении Pandas!


In [1]:
# простые задания без описания:

In [2]:
import pandas as pd
import numpy as np

pd.Series([0,1,2,3,4], index = ['a', 'b', 'c', 'e', 'd'])

a    0
b    1
c    2
e    3
d    4
dtype: int64

In [3]:
s = pd.Series(["a", "b", "c"],
              name="vals")
s.to_frame()

vals
0    a
1    b
2    c

In [4]:
s1 = pd.Series(list('abced'))
s2 = pd.Series(np.arange(5))

p = pd.concat([s1,s2], axis=1, keys = ['col1', 'col2'])
p

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [5]:
s = pd.Series(list('abced'), name="characters")
s.index.name = 'XXX'
s

XXX
0    a
1    b
2    c
3    e
4    d
Name: characters, dtype: object

In [6]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])
s1[~s1.isin(s2)]

0    1
1    2
2    3
dtype: int64

In [7]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

s3 = pd.Series(np.union1d(s1, s2))
s4 = pd.Series(np.intersect1d(s1,s2))
s5 = s3[~s3.isin(s4)]
print(s5)


0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64


In [8]:
 pd.Series([5,6,7])

0    5
1    6
2    7
dtype: int64

In [9]:
 pd.Series([5,6,7]).index.to_series()

0    0
1    1
2    2
dtype: int64

In [10]:
# расчет персентилей
def solution(ser):
    m0 = np.percentile(ser, 0)
    m25 = np.percentile(ser, 25)
    m50 = np.percentile(ser, 50)
    m75 = np.percentile(ser, 75)
    m100 = np.percentile(ser, 100)
    result = pd.Series([m0, m25, m50, m75, m100])
    # or
    result = pd.Series(np.percentile(ser, [0, 25, 50, 75, 100]))
    return result

ser = [1,2,5,7]



solution(ser)

0    1.00
1    1.75
2    3.50
3    5.50
4    7.00
dtype: float64

In [11]:
s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))
result = s.value_counts()
s.isin(result[:2].index)

0      True
1      True
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12     True
13     True
14    False
15     True
16    False
17     True
18    False
19     True
20    False
21    False
22     True
23    False
24     True
25    False
26    False
27     True
28     True
29     True
30    False
31    False
32     True
33    False
34    False
35    False
dtype: bool

In [13]:
"""
Доработайте код таким образом, чтобы оставить только 2 наиболее 
встречающихся значения, а для остальных установите значение 
'Yet another value'.

Функция solution должна возвращать серию.
"""

def solution():
    s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))
    counts = s.value_counts()
    result = s.where(s.isin(counts[:2].index),  'Yet another value')
    
    # or
    
    result = pd.Series(np.where(s.isin(result[:2].index), s, 'Yet another value'))
    
    return result

solution()

0     Yet another value
1     Yet another value
2     Yet another value
3     Yet another value
4     Yet another value
5     Yet another value
6     Yet another value
7     Yet another value
8     Yet another value
9     Yet another value
10    Yet another value
11    Yet another value
12    Yet another value
13    Yet another value
14    Yet another value
15    Yet another value
16    Yet another value
17    Yet another value
18    Yet another value
19    Yet another value
20    Yet another value
21    Yet another value
22    Yet another value
23    Yet another value
24    Yet another value
25    Yet another value
26    Yet another value
27    Yet another value
28    Yet another value
29    Yet another value
30    Yet another value
31    Yet another value
32    Yet another value
33    Yet another value
34    Yet another value
35    Yet another value
dtype: object

In [14]:
# Разбейте все значения из pandas.Series (переменная s1) на 3 интервала равного размера. 
# Функция должна вернуть серию

def solution():
    s1 = pd.Series(reversed(range(0, 10)))
    result = pd.qcut(s1, 3)
    return result

solution()

0       (6.0, 9.0]
1       (6.0, 9.0]
2       (6.0, 9.0]
3       (3.0, 6.0]
4       (3.0, 6.0]
5       (3.0, 6.0]
6    (-0.001, 3.0]
7    (-0.001, 3.0]
8    (-0.001, 3.0]
9    (-0.001, 3.0]
dtype: category
Categories (3, interval[float64]): [(-0.001, 3.0] < (3.0, 6.0] < (6.0, 9.0]]

In [15]:
# Преобразуйте pandas.Series (переменная s1) в pandas.DataFrame размером 2 х 5:

def solution():
    s1 = pd.Series(range(0, 10))
    result = pd.DataFrame(s1.to_numpy().reshape(2,5))
    return result

solution()

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [16]:
# Найдите индексы значений, которые кратны

def solution():
    s1 = pd.Series([5, 10, 2, 3, 9, 12, 1])
    result = np.argwhere(s1.values % 2 == 0)
    return result
    
solution()

array([[1],
       [2],
       [5]])

In [17]:
# Создайте новый pandas.Series из элементов, которые находятся по индексам: 0, 7, 12, 15, 19.

def solution():
    s1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
    indx = [0, 7, 12, 15, 19]
    result = s1.take(indx)
    return result
    
solution()

0     a
7     h
12    m
15    p
19    t
dtype: object

In [18]:
s1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
df = pd.DataFrame(s1).take((0, 7, 12, 15, 19))
df[0].rename(None, inplace=True)


0     a
7     h
12    m
15    p
19    t
dtype: object

In [19]:
# Преобразуйте элементы pandas.Series (переменная s1) из строк в даты.

def solution():
    s1 = pd.Series(['01 Jan 2022', '02-02-2022', '20220303', '2022/04/04', '2022-05-05', '2022-06-06T12:20'])
    result = pd.to_datetime(s1)
    # or
    result = pd.Series(s1, dtype='datetime64')
    
    return result

solution()

0   2022-01-01 00:00:00
1   2022-02-02 00:00:00
2   2022-03-03 00:00:00
3   2022-04-04 00:00:00
4   2022-05-05 00:00:00
5   2022-06-06 12:20:00
dtype: datetime64[ns]

In [20]:
pd.DataFrame({'year': [2015, 2016],
                   'month': [2, 3],
                   'day': [4, 5]})

year  month  day
0  2015      2    4
1  2016      3    5

In [21]:
pd.to_datetime(pd.DataFrame({'year': [2015, 2016],
                             'month': [2, 3],
                             'day': [4, 5]}))

0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]

In [22]:
s1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
s2 = pd.Series([1, 3, 10, 13])
s1.isin(s2).to_list()
# s1.values % 2 == 0

[True, False, False, False, True, True, False, False, True]

In [23]:
# Объект pandas.Series (переменная s1) содержит некоторые числовые значения. 
# Для значений хранящихся в s2 определите индексы под которыми они 
# хранятся  в s1. Функция должна вернуть список (python list):


def solution():
    s1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
    s2 = pd.Series([1, 3, 10, 13])
    result = [np.argwhere([s1 == value])[0][1] for value in s2.values if value in s1.values]
    return result


solution()

[5, 4, 0, 8]

In [24]:
# Даны следующие ряды данных:
# s_forecast - ряд прогнозных значений
# s_real - ряд фактических значений
# Вычислите среднеквадратичную ошибку. MSE

def solution():
    s_forecast = pd.Series(range(10))
    s_real  = pd.Series(reversed(range(10)))
    result = np.mean((s_forecast - s_real) ** 2) 
    return result

solution()

33.0

In [25]:
# Измените первый символ каждого слова на верхний регистр.

def solution():
    s1 = pd.Series(['the', 'weather', 'is', 'fine']) 
    result = s1.str.capitalize()
    # or
    result = s1.apply(lambda x: x[0].upper() + x[1:])
    return result

In [26]:
# Подсчитайте количество символов в каждом слове. Функция solution 
# должна вернуть серию:

def solution():
    s1 = pd.Series(['the', 'weather', 'is', 'fine']) 
    result = s1.str.len()
    return result

solution()

0    3
1    7
2    2
3    4
dtype: int64

In [27]:
pd.to_datetime(s1).dt

In [28]:
# Вытяните день месяца, номер недели, 
# день года и день недели из серии (s1)

from collections import defaultdict

s1 = pd.Series(['05 Jan 2021', '02-04-2021', '20210403', '2021/06/04', '2021-03-05', '2021-03-06T12:20'])

out = defaultdict(list)
for i in pd.to_datetime(s1):
    out["Date"].append(i.day)
    out["Week number"].append(i.week)
    out["Day number of year"].append(i.dayofyear)
    out["Day of week"].append(i.day_name())
    
for key in out:
    print(f"{key}: {out[key]}")

# or  
out = defaultdict(list)
date_t = pd.to_datetime(s1).dt
for key, val  in zip(["Date", "Week number", "Day number of year", "Day of week"],
                [date_t.day, date_t.isocalendar().week, date_t.dayofyear, date_t.day_name()]):
    out[key].extend(val)

for key in out:
    print(f"{key}: {out[key]}")
    

Date: [5, 4, 3, 4, 5, 6]
Week number: [1, 5, 13, 22, 9, 9]
Day number of year: [5, 35, 93, 155, 64, 65]
Day of week: ['Tuesday', 'Thursday', 'Saturday', 'Friday', 'Friday', 'Saturday']
Date: [5, 4, 3, 4, 5, 6]
Week number: [1, 5, 13, 22, 9, 9]
Day number of year: [5, 35, 93, 155, 64, 65]
Day of week: ['Tuesday', 'Thursday', 'Saturday', 'Friday', 'Friday', 'Saturday']


In [29]:
# Измените даты лежащие в серии (s1) таким образом чтобы они 
# начинались с 10-го числа соответствующего месяца.

s1 = pd.Series(['Jan 2022', 'Feb 2022', 'Mar 2022'])

s1 = pd.to_datetime(s1)
delta =pd.Timedelta(days=9)
s1 + delta

0   2022-01-10
1   2022-02-10
2   2022-03-10
dtype: datetime64[ns]

In [30]:
# Из серии (s1) вытяните слова, содержащие не менее 2 гласных.

s1 = pd.Series(['Apple', 'Orange', 'Plan', 'Sky', 'Money'])

s1[(s1.str.count('[aeiouyAEIOUY]')) >= 2]

# or

s2 = s1.apply((lambda x: sum(1 if i.lower() in 'aeiouy' else 0 for i in x)))
s2 = s2.where(s2 >= 2).dropna()
s1 = s1.iloc[s2.index]
s1

0     Apple
1    Orange
4     Money
dtype: object

In [31]:
# Извлеките корректные почтовые адреса из серии (s1). 
# Используйте pattern для этой задачи.

s1 = pd.Series(['teach pandas at stepik.com', 'help@stepik.com', 'user@t.co', 'lovepandas@google.com'])

pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
s1[s1.str.contains(pattern)]

# or

s1[s1.str.findall(pattern).explode().notnull()]

1          help@stepik.com
2                user@t.co
3    lovepandas@google.com
dtype: object

In [32]:
# Вычислите среднее значение веса каждого фрукта.

fruit_list = ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
weights_list =  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

fruits = pd.Series(fruit_list)
weights = pd.Series(weights_list)

weights.index = fruits
weights.groupby(weights.index).agg(np.mean)

apple     6.0
banana    4.0
carrot    5.8
dtype: float64

In [33]:
# Вычислить евклидово расстояние между рядами (точками) X и Y

X = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Y = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

((X-Y) ** 2).sum() ** 0.5

18.16590212458495

In [34]:
# Определите индексы пиков (значения, окруженные меньшими значениями
# с обеих сторон).

s1 = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

indx = []
for i in range(1, s1.size):
    if s1[i-1] < s1[i] > s1[i+1]:
        indx.append(i)
print(f"[{' '.join(map(str, s1[indx].index))}]")

# or 

comp = s1.rolling(3, center=True).max()
res = s1 - comp
print(res[res==0].index.values)

# or 
print(np.array(s1.loc[np.where(np.diff(s1) < 0)].index))

# or

print(s1[(s1.shift(-1) < s1) & (s1 > s1.shift(1))].index.values)
print(np.array(s1.index[(s1 > s1.shift(-1)) & (s1 > s1.shift(1))]))

[1 5 7]
[1 5 7]
[1 5 7]
[1 5 7]
[1 5 7]


In [35]:
s1 = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

s0 = s1.shift(-1)
s2 = s1.shift(1)
s1[(s0 < s1) & (s1 > s2)].index

Int64Index([1, 5, 7], dtype='int64')

In [36]:
# В серии (s1) находятся даты с 1 по 8 января 2022 года. 
# Однако некоторые даты и значения к датам пропущены. 
# Сделайте так, чтобы все отсутствующие даты отображались и 
# заполнялись значением из предыдущей даты.

s1 = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2022-01-01', '2022-01-03', '2022-01-06', '2022-01-08']))
print(s1.asfreq("1D").fillna(method="ffill"))
# or
print(s1.resample('1D').ffill().ffill())

2022-01-01     1.0
2022-01-02     1.0
2022-01-03    10.0
2022-01-04    10.0
2022-01-05    10.0
2022-01-06     3.0
2022-01-07     3.0
2022-01-08     3.0
Freq: D, dtype: float64
2022-01-01     1.0
2022-01-02     1.0
2022-01-03    10.0
2022-01-04    10.0
2022-01-05    10.0
2022-01-06     3.0
2022-01-07     3.0
2022-01-08     3.0
Freq: D, dtype: float64


In [37]:
"""
Отредактируйте название колонок датафрейма (df) следующим образом:
1. user -> user_name
2. все точки в названии колонок заменить нижним подчёркиванием
Выведите названия колонок после преобразования.
"""

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex'], 'user.balance' : [500, 200, 0], 'user.age' : [34, 25, 18], 'user.group' : ['A', 'B', 'A']})

print(pd.Index(pd.Series(df.columns).replace(["user$", "\."],["user_name", "_"], regex=True)))

# or

df = df.rename({'user': 'user_name'}, axis='columns')
df.columns.map(lambda x: x.replace('.', '_'))

df.rename(columns={'user':'user_name'}, inplace=True)
df.rename(columns=lambda x: x.replace('.','_'), inplace=True)



Index(['user_name', 'user_balance', 'user_age', 'user_group'], dtype='object')


In [38]:
# Проверьте, имеются ли пропущенные значения в датафрейме (df).

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex'], 'user.balance' : [500, None, 0], 'user.age' : [34, 25, 18], 'user.group' : ['A', 'B', 'A']})
print(any(df.isnull()))

True


In [39]:
# Подсчитайте количество пропущенных значений в каждом столбце.

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den'], 'user.balance' : [500, None, 0, None], 'user.age' : [34, None, 18, 43], 'user.group' : ['A', 'B', 'A', 'B']})
print(df.isnull().sum())

user            0
user.balance    2
user.age        1
user.group      0
dtype: int64


In [40]:
# Замените отсутствующие значения в столбцах user.speed и 
# user.bag_weight их соответствующими средними значениями.

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den'], 'user.speed' : [40, None, 42, 35], 'user.bag_weight' : [8, None, 2, 4]})

print(df.fillna(df.mean(axis=0)).iloc[:, 1:])

# or

df = df.select_dtypes(exclude='object')
print(df.fillna(df.mean()))

   user.speed  user.bag_weight
0        40.0         8.000000
1        39.0         4.666667
2        42.0         2.000000
3        35.0         4.000000
   user.speed  user.bag_weight
0        40.0         8.000000
1        39.0         4.666667
2        42.0         2.000000
3        35.0         4.000000


In [41]:
# Используйте метод apply, чтобы заменить отсутствующие значения в user.speed средним значением столбца, 
# а в user.bag_weight — медианой столбца.


df = df.fillna({'user.speed': np.mean, 'user.bag_weight': np.median})
print(df)

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den'], 'user.speed' : [40, None, 42, 35], 'user.bag_weight' : [8, None, 2, 4]})
df['user.speed'] = df['user.speed'].fillna(df['user.speed'].mean())
df['user.bag_weight'] = df['user.bag_weight'].fillna(df['user.bag_weight'].median())
print(df)

#or

df[['user.speed','user.bag_weight']] = df.apply({'user.speed': lambda x: x.fillna(x.mean()), 'user.bag_weight': lambda x: x.fillna(x.median())})
print(df)

                          user.speed                      user.bag_weight
0                               40.0                                  8.0
1  <function mean at 0x7fcc68261280>  <function median at 0x7fcc68124550>
2                               42.0                                  2.0
3                               35.0                                  4.0
   user  user.speed  user.bag_weight
0  Ivan        40.0              8.0
1  Petr        39.0              4.0
2  Alex        42.0              2.0
3   Den        35.0              4.0
   user  user.speed  user.bag_weight
0  Ivan        40.0              8.0
1  Petr        39.0              4.0
2  Alex        42.0              2.0
3   Den        35.0              4.0


In [42]:
def foo(data):
    if data.name == "user.speed":
        data = data.fillna(data.mean())
    elif data.name == "user.bag_weight":
        data = data.fillna(data.median())
    return data


df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den'], 'user.speed' : [40, None, 42, 35], 'user.bag_weight' : [8, None, 2, 4]})
df = df.apply(foo)
print(df)

   user  user.speed  user.bag_weight
0  Ivan        40.0              8.0
1  Petr        39.0              4.0
2  Alex        42.0              2.0
3   Den        35.0              4.0


In [43]:
import numpy

m = np.array([[0.8, 0.2, 0.2],
              [0.2, 0.8, 0.2], 
              [0.2, 0.2, 0.8], 
              [0.2, 0.2, 0.2]])

print(1 - m.prod(axis=1).sum())   

0.8959999999999999


In [44]:
# Поменяйте столбцы А и Е местами в датафрейме:

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df = df.iloc[:,[4,1,2,3,0]]
df

e   b   c   d   a
0   4   1   2   3   0
1   9   6   7   8   5
2  14  11  12  13  10
3  19  16  17  18  15

In [45]:
# Поменяйте порядок столбцов в датафрейме от Е до А.

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

df[reversed(df.columns)]

e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

In [46]:
# Выведите на экран строки датафрейма с шагом 2.

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den', 'Viktor'], 'user.speed' : [40, None, 42, 35, 60], 'user.bag_weight' : [8, None, 2, 4, 19]})
df.iloc[df.index % 2 == 0, :]

user  user.speed  user.bag_weight
0    Ivan        40.0              8.0
2    Alex        42.0              2.0
4  Viktor        60.0             19.0

In [47]:
# Создайте составной индекс на основе колонок user и user.number 
# для датафрейма:

df = pd.DataFrame(data = {'user' : ['Ivan', 'Petr', 'Alex', 'Den', 'Viktor'], 'user.number' : ['222-333', None, '222-555', '222-666', '222-777'], 'user.speed' : [40, None, 42, 35, 60], 'user.bag_weight' : [8, None, 2, 4, 19]})

df['user.number'] = df['user.number'].fillna('missing')
df.index = df['user'] + '_' + df['user.number']
df

user user.number  user.speed  user.bag_weight
Ivan_222-333      Ivan     222-333        40.0              8.0
Petr_missing      Petr     missing         NaN              NaN
Alex_222-555      Alex     222-555        42.0              2.0
Den_222-666        Den     222-666        35.0              4.0
Viktor_222-777  Viktor     222-777        60.0             19.0

In [48]:
# Как задать максимальное количество выводимых строк датафрейма?

pd.set_option('display.max_rows', 12)
# pd.reset_option('all')

In [49]:
# Для столбца А найдите индекс строки в которой находится второе 
# наибольшее значение.

df = pd.DataFrame([[16,24,29],[1,10,16],[26,21,10],[3,3,8],[6,17,17],[2,25,14],[9,13,21],[27,24,17],[19,29,1],[20,24,6]], columns=list('abc'))
df['a'][~df['a'].index.isin([df['a'].argmax()])].argmax()

#or

df['a'].sort_values(ascending=False).index[1]

2

In [50]:
# Выведите последние две строки датафрейма, сумма ячеек которых 
# больше 100.

df = pd.DataFrame([[23,33,16,35],
                   [24,20,13,10],
                   [32,33,30,28],
                   [13,32,36,18],
                   [25,27,31,10],
                   [35,13,36,21],
                   [32,32,25,17],
                   [34,24,23,19]])
df['sum'] = df.sum(axis=1)
df[df['sum'] > 100].iloc[-2:, :-1]

0   1   2   3
5  35  13  36  21
6  32  32  25  17

In [51]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######

df[:3]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [52]:
df.loc[df.index[[3, 4, 8]], ['animal', 'age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [53]:
df[df['visits'] > 2]

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [54]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [55]:
df.loc['f', 'age'] = 1.5

In [56]:
df.groupby(['animal'])['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

In [57]:
df[['age']].squeeze()

a    2.5
b    3.0
c    0.5
d    NaN
e    5.0
f    1.5
g    4.5
h    NaN
i    7.0
j    3.0
Name: age, dtype: float64

In [58]:
# Отсортируйте датафрейм по столбцу age в порядке убывания, а затем 
# по столбцу visits в порядке возрастания. 

df = df.sort_values(by = ['age', 'visits'], ascending=[False, True])
print(df)


  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes


In [59]:
# Столбец priority содержит строковые значения yes и no. 
# Замените их на булевы True и False

df['priority'] = df['priority'].map({'yes': True, 'no': False})
df

animal  age  visits  priority
i    dog  7.0       2     False
e    dog  5.0       2     False
g  snake  4.5       1     False
j    dog  3.0       1     False
b    cat  3.0       3      True
a    cat  2.5       1      True
f    cat  1.5       3     False
c  snake  0.5       2     False
h    cat  NaN       1      True
d    dog  NaN       3      True

In [60]:
"""
Определите средний возраст для каждого типа животного и количества 
посещений.

(Другими словами, постройте сводную таблицу, где каждая строка — 
это тип животного, каждый столбец — количество посещений, 
а значения — средний возраст).
"""

pd.pivot_table(df, values='age', index='animal', 
               columns='visits', aggfunc=np.mean)

visits    1    2     3
animal                
cat     2.5  NaN  2.25
dog     3.0  6.0   NaN
snake   4.5  0.5   NaN

In [61]:
# Вычтите среднее значение строки из каждого элемента в строке.

df = pd.DataFrame([[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364], [0.094699, 0.283184, 0.216221]])

df['mean'] = df.mean(axis=1)
df.iloc[:, :-1].apply(lambda x: x - df['mean'])

# or
df.apply(lambda x: x - x.mean(), axis=1)
df.sub(df.mean(axis=1), 0)

0         1         2  mean
0 -0.469429 -0.032952  0.502381   0.0
1  0.280649  0.092736 -0.373386   0.0
2 -0.103336  0.085149  0.018186   0.0

In [62]:
# В каком столбце чисел сумма наименьшая? 
# Выведите на экран название этого столбца.

df = pd.DataFrame([[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364], [0.094699, 0.283184, 0.216221]], columns=list('abc'))

print(df.sum(axis=0).idxmin())
print(df.sum().sort_values().index[0])


a
a


In [63]:
# Как подсчитать, сколько уникальных строк имеет датафрейм (т. е. игнорировать все повторяющиеся строки)?

df = pd.DataFrame([[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364], [0.020448, 0.456925, 0.992258], [0.094699, 0.283184, 0.216221]], columns=list('abc'))
print(len(df.drop_duplicates(keep=False)))


2


In [64]:
# Имеется датафрейм состоящий из 10 столбцов чисел с плавающей запятой. 
# Ровно 5 записей в каждой строке являются значениями NaN. Для каждой строки датафрейма найдите столбец, содержащий третье значение NaN.

nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)
for i in range(12):
    df = pd.concat([df, df])
df

a   b     c     d     e     f     g     h     i     j
0   0.04 NaN   NaN  0.25   NaN  0.43  0.71  0.51   NaN   NaN
1    NaN NaN   NaN  0.04  0.76   NaN   NaN  0.67  0.76  0.16
2    NaN NaN  0.50   NaN  0.31  0.40   NaN   NaN  0.24  0.01
3   0.49 NaN   NaN  0.62  0.73  0.26  0.85   NaN   NaN   NaN
4    NaN NaN  0.41   NaN  0.05   NaN  0.61   NaN  0.48  0.68
..   ...  ..   ...   ...   ...   ...   ...   ...   ...   ...
0   0.04 NaN   NaN  0.25   NaN  0.43  0.71  0.51   NaN   NaN
1    NaN NaN   NaN  0.04  0.76   NaN   NaN  0.67  0.76  0.16
2    NaN NaN  0.50   NaN  0.31  0.40   NaN   NaN  0.24  0.01
3   0.49 NaN   NaN  0.62  0.73  0.26  0.85   NaN   NaN   NaN
4    NaN NaN  0.41   NaN  0.05   NaN  0.61   NaN  0.48  0.68

[20480 rows x 10 columns]

In [65]:
%%time
num = 0
out = pd.Series([0]*len(df))
for i in range(len(df)):
    for indx, j in enumerate(df.iloc[i, :].values):
        if np.isnan(j):
            num += 1
            if num == 3:
                out[i] = df.columns[indx]
                break
    num = 0
out

CPU times: user 2.62 s, sys: 0 ns, total: 2.62 s
Wall time: 2.63 s


0        e
1        c
2        d
3        h
4        d
        ..
20475    e
20476    c
20477    d
20478    h
20479    d
Length: 20480, dtype: object

In [66]:
# or
pd.DataFrame(df.isna().cumsum(axis=1) == 3).idxmax(1)
df.isna().cumsum(axis=1).eq(3).idxmax(axis=1)

0    e
1    c
2    d
3    h
4    d
    ..
0    e
1    c
2    d
3    h
4    d
Length: 20480, dtype: object

In [67]:
"""
Датафрейм содержит колонку grps (название некоторой группы) и колонку целочисленных значений vals.  
Для каждой группы найдите сумму трех наибольших значений.
"""

df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
df.groupby(by='grps')['vals'].agg(lambda x: x.sort_values(ascending=False)[:3].sum())

df.groupby('grps')['vals'].nlargest(3).sum(level = 1)
df.groupby('grps')['vals'].nlargest(3).groupby('grps').sum()

grps
a    409
b    156
c    345
Name: vals, dtype: int64

In [68]:
"""
Датафрейм df имеет два целочисленных столбца «A» и «B». 
Значения в «A» находятся в диапазоне от 1 до 100 (включительно).

Для каждой группы из 10 последовательных целых чисел в столбце А 
(т. е. (0, 10], (10, 20], ...) вычислите сумму соответствующих 
значений в столбце B.
"""

df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

df.index = pd.cut(df["A"], np.arange(0, 101, 10))
# or
# df.index = pd.cut(df['A'], bins = 10, right=True, precision=-1)

print(df.groupby(df.index)["B"].sum())

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64


In [69]:
# Создайте список индексов столбцов и строк для 3 самых 
# больших значений в предлагаемом датафрейме.

df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))
df

0   1   2   3   4   5   6   7
0  38  38  46  46  13  24   3  54
1  18  47   4  42   8  66  50  46
2  62  36  19  19  77  17   7  63
3  28  47  46  65  63  12  16  24
4  14  51  34  56  29  59  92  79
5  58  76  96  45  38  76  58  40
6  10  34  48  40  37  23  41  26
7  55  70  91  27  79  92  20  31

In [70]:
max3 = np.sort(df.values.reshape(1, -1))[0][-3:]
list(df[df.isin(max3)].idxmax().dropna().map(int).items())

[(2, 5), (5, 7), (6, 4)]

In [71]:
df.unstack().sort_values()[-3:].index.to_list()

[(5, 7), (6, 4), (2, 5)]

In [72]:
"""
Создайте новый столбец patched_vals, который содержит те же значения
, что и vals, но отрицательные значения заменить средним значением 
группы.
"""

df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
mean_ = df[df["vals"] > 0].groupby("grps")["vals"].mean()
df["patched_vals"] = np.where(df["vals"] > 0, df["vals"], mean_[df["grps"]])
df


vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
..   ...  ...           ...
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6

[15 rows x 3 columns]

In [73]:
# уменьшение размерности

import numpy as np

P2_old = np.array([1.5, 2, 2.5, 3, 3.5, 4])
P1_old = np.array([0.5, 1, 1.5, 2, 2.5, 3])

center_P1 = P1_old.mean()
center_P2 = P2_old.mean()

P_new = np.sqrt((P1_old - center_P1) ** 2 + (P2_old - center_P2) ** 2)
P_new

array([1.76776695, 1.06066017, 0.35355339, 0.35355339, 1.06066017,
       1.76776695])

In [74]:
# Найдите сумму всех значений, которые указаны для среды (Wednesday)

dti = pd.date_range(start='2021-01-01', end='2021-12-31', freq='B') 
s = pd.Series(np.random.RandomState(30).rand(len(dti)), index=dti)
s[s.index.day_name() == "Wednesday"].sum()

23.508792429234397

In [75]:
# Для каждого месяца найдите среднее значение.

dti = pd.date_range(start='2021-01-01', end='2021-12-31', freq='B') 
s = pd.Series(np.random.RandomState(30).rand(len(dti)), index=dti)

s.groupby(pd.Grouper(freq='M')).mean()

#or

s.resample("M").mean()

2021-01-31    0.507726
2021-02-28    0.462692
2021-03-31    0.478605
2021-04-30    0.564210
2021-05-31    0.387735
2021-06-30    0.451999
2021-07-31    0.541958
2021-08-31    0.553241
2021-09-30    0.507650
2021-10-31    0.453517
2021-11-30    0.490528
2021-12-31    0.495812
Freq: M, dtype: float64

In [76]:
"""
Превратите датафрейм в квадрат с максимально возможной длиной стороны n, 
убрав отрицательные значения. При необходимости удалите наименьшие значения.
Порядок положительных чисел в результате должен оставаться таким же, как и 
в оригинале.

Подсказка:

Шаг 1: Удалите отрицательные значения

Шаг 2: Определите наибольший размер стороны квадрата n, который может получиться

Шаг 3: Постройте квадрат со стороной n из ТОП n^2 наибольших значений
"""

df = pd.DataFrame(np.random.RandomState(30).randint(-20, 50, 100).reshape(10,-1))
df

0   1   2   3   4   5   6   7   8   9
0  17  17  25  25  -8   3 -18  33  -3  26
1 -17  21 -13  45  29  25  41  15  -2  -2
2  -4 -14  42   7  26  25  44  42  -9  -5
3   3  -7  30  13  35   8  38  37  24  17
4  37  19 -11  13  27  19  16   2  20   5
5  34  49   6  -1  10  29  32  24  41  14
6  23   8  40  31  21  36  -4  19  13 -11
7  -9 -16   8 -10  -3  38 -11  25  28  35
8  -1  25  11   3  -9   9  24   9  -1  31
9  35  32   3  41 -14  19  10  24  27  -7

In [77]:
out = df[df > 0].values.reshape(1,-1)
out = out[~np.isnan(out)]
power = True
while power:
    n = np.sqrt(len(out))
    if n == int(n):
        power = False
    else:
        out = np.delete(out, np.where(out == out.min())[0][0])
out.reshape(int(n), int(n))    

array([[17., 17., 25., 25., 33., 26., 21., 45.],
       [29., 25., 41., 15., 42., 26., 25., 44.],
       [42., 30., 13., 35., 38., 37., 24., 17.],
       [37., 19., 13., 27., 19., 16., 20., 34.],
       [49., 10., 29., 32., 24., 41., 14., 23.],
       [40., 31., 21., 36., 19., 13.,  8., 38.],
       [25., 28., 35., 25., 11.,  9., 24.,  9.],
       [31., 35., 32., 41., 19., 10., 24., 27.]])

In [78]:
df = pd.DataFrame(np.random.RandomState(30).randint(-20, 50, 100).reshape(10,-1))
df = df.to_numpy(dtype='float')
df = df[df>=0]
n = int(np.sqrt(len(df)))
df = df[sorted(df.argsort()[-n * n:])]
print(df.reshape(n, n))

[[17. 17. 25. 25. 33. 26. 21. 45.]
 [29. 25. 41. 15. 42. 26. 25. 44.]
 [42. 30. 13. 35. 38. 37. 24. 17.]
 [37. 19. 13. 27. 19. 16. 20. 34.]
 [49. 10. 29. 32. 24. 41. 14. 23.]
 [40. 31. 21. 36. 19. 13.  8. 38.]
 [25. 28. 35. 25. 11.  9. 24.  9.]
 [31. 35. 32. 41. 19. 10. 24. 27.]]


In [79]:
df = pd.DataFrame(np.random.RandomState(30).randint(-20, 50, 100).reshape(10,-1))
i = int(df[df>=0].count().sum()**.5)
s = pd.Series(df.values.reshape(-1)).nlargest(i**2, keep='last') \
                .sort_index().astype('float').values.reshape(i, i)
print(s)

[[17. 17. 25. 25. 33. 26. 21. 45.]
 [29. 25. 41. 15. 42. 26. 25. 44.]
 [42. 30. 13. 35. 38. 37. 24. 17.]
 [37. 19. 13. 27. 19. 16. 20. 34.]
 [49. 10. 29. 32. 24. 41. 14. 23.]
 [40. 31. 21. 36. 19. 13.  8. 38.]
 [25. 28. 35. 25. 11.  9. 24.  9.]
 [31. 35. 32. 41. 19. 10. 24. 27.]]


In [80]:
# Измените порядок строк датафрейма

df = pd.DataFrame(np.arange(25).reshape(5, -1))
df.iloc[[0, 2, 1, 3, 4] , :].reset_index(drop=True)

# or

df.index = [0, 2, 1, 3, 4]
df.sort_index()

df = pd.DataFrame(np.arange(25).reshape(5, -1))
df.rename({1 : 2, 2 : 1}, axis=0).sort_index()

df = pd.DataFrame(np.arange(25).reshape(5, -1))
df.loc[1], df.loc[2] = df.loc[2].copy(), df.loc[1].copy()

df = pd.DataFrame(np.arange(25).reshape(5, -1))
df.iloc[1:3] = df.iloc[1:3][::-1]

df.iloc[1], df.iloc[2] = df.iloc[2].copy(), df.iloc[1].copy()
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [81]:
df.index[::-1]

RangeIndex(start=4, stop=-1, step=-1)

In [82]:
# Измените порядок строк датафрейма таким образом, чтобы последние стали 
# первыми, а первые последними (reverse).

df = pd.DataFrame(np.arange(25).reshape(5, -1))

df.iloc[:] = df.iloc[::-1]
df = df.set_axis(range(len(df)-1,-1,-1))

#or
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df = df.iloc[::-1]
df

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [83]:
# Выполните one-hot encoding для столбца А и добавьте результат к датафрейму

df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
print(df)
pd.concat([pd.get_dummies(df['a']), df.drop("a", axis=1)], axis=1)
# pd.get_dummies(df, columns=['a'])

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [84]:
# тоже с ванхот
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)
ohe.fit(df[['a']])
temp_df = pd.DataFrame(data=ohe.transform(df[['a']]), columns=ohe.get_feature_names((['a'])))
pd.concat([temp_df, df.drop("a", axis=1)], axis=1)

a_0  a_5  a_10  a_15  a_20   b   c   d   e
0  1.0  0.0   0.0   0.0   0.0   1   2   3   4
1  0.0  1.0   0.0   0.0   0.0   6   7   8   9
2  0.0  0.0   1.0   0.0   0.0  11  12  13  14
3  0.0  0.0   0.0   1.0   0.0  16  17  18  19
4  0.0  0.0   0.0   0.0   1.0  21  22  23  24

In [85]:
# если в тесте другие значения (нет 25), dummy так не умеет,
# а OneHotEncoder может, делает пустой столбец
test = pd.DataFrame(np.arange(30).reshape(6,-1), columns=list('abcde'))
test.iloc[[4, 5], 0] = 10
test

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  10  21  22  23  24
5  10  26  27  28  29

In [86]:
temp_df = pd.DataFrame(data=ohe.transform(test[['a']]).astype(int), columns=ohe.get_feature_names((['a'])))
pd.concat([temp_df, test.drop("a", axis=1)], axis=1)

a_0  a_5  a_10  a_15  a_20   b   c   d   e
0    1    0     0     0     0   1   2   3   4
1    0    1     0     0     0   6   7   8   9
2    0    0     1     0     0  11  12  13  14
3    0    0     0     1     0  16  17  18  19
4    0    0     1     0     0  21  22  23  24
5    0    0     1     0     0  26  27  28  29

In [87]:
# Определите имя столбца с наибольшим количеством строковых максимумов. 

df = pd.DataFrame(np.random.RandomState(30).randint(1,100, 40).reshape(10, -1))



df = df.apply(lambda x: (x == x.max()), axis=1).astype(int)
df.sum(axis=0).argmax()

3

In [88]:
%%time
# Создайте новый столбец таким образом, чтобы каждая строка содержала 
# номер наиболее удалённой строки-записи по евклидову расстоянию.

df = pd.DataFrame(np.random.RandomState(30).randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
# df = pd.concat([df]*500)
print(df)

def solution(df):
    euclid = {}
    for i, v in enumerate(df.values):
        indx = df.index[i]
        euclid[indx] = (((df.drop(indx, axis=0) - v) ** 2).sum(axis=1).pow(0.5))\
                .sort_values(ascending=False)
    df["nearest_row"] = df.apply(lambda x: euclid[x.name].index[0], axis=1)
    df["dist"] = df.apply(lambda x: euclid[x.name][0].round().astype('int'), axis=1)
    return df

solution(df)

    p   q   r   s
a  38  38  46  46
b  13  24   3  54
c  18  47   4  42
d   8  66  50  46
e  62  36  19  19
f  77  17   7  63
g  28  47  46  65
h  63  12  16  24
i  14  51  34  56
j  29  59  92  79
CPU times: user 16.9 ms, sys: 0 ns, total: 16.9 ms
Wall time: 22.5 ms


p   q   r   s nearest_row  dist
a  38  38  46  46           f    61
b  13  24   3  54           j   100
c  18  47   4  42           j    97
d   8  66  50  46           f    96
e  62  36  19  19           j   103
f  77  17   7  63           j   107
g  28  47  46  65           h    71
h  63  12  16  24           j   110
i  14  51  34  56           f    77
j  29  59  92  79           h   110

In [89]:
%%time
df = pd.DataFrame(np.random.RandomState(30).randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
# df = pd.concat([df]*500)

def solution(df):
    temp = df.apply(lambda x: (df - x).pow(2).sum(axis=1).pow(0.5), axis=1)
    df['nearest_row'] = temp.idxmax()
    df['dist'] =  temp.max().round(). astype('int')
    return df

solution(df)

CPU times: user 12.8 ms, sys: 0 ns, total: 12.8 ms
Wall time: 11.9 ms


p   q   r   s nearest_row  dist
a  38  38  46  46           f    61
b  13  24   3  54           j   100
c  18  47   4  42           j    97
d   8  66  50  46           f    96
e  62  36  19  19           j   103
f  77  17   7  63           j   107
g  28  47  46  65           h    71
h  63  12  16  24           j   110
i  14  51  34  56           f    77
j  29  59  92  79           h   110

In [90]:
# Определите максимально возможное значение корреляции каждого столбца по 
# сравнению с другими столбцами датафрейма.

df = pd.DataFrame(np.random.RandomState(25).randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

df = df.corr()
print(df)
df.apply(lambda x: abs(x[x[x != 1].abs().argmax() + 1]).round(2))

          p         q         r         s         t         u         v  \
p  1.000000 -0.512107 -0.767901  0.139413  0.052365  0.544037  0.335403   
q -0.512107  1.000000  0.209535 -0.424986 -0.013054 -0.639377  0.142553   
r -0.767901  0.209535  1.000000 -0.187936  0.295132 -0.408626 -0.171527   
s  0.139413 -0.424986 -0.187936  1.000000 -0.152527  0.845489 -0.606281   
t  0.052365 -0.013054  0.295132 -0.152527  1.000000 -0.019302  0.319836   
u  0.544037 -0.639377 -0.408626  0.845489 -0.019302  1.000000 -0.210305   
v  0.335403  0.142553 -0.171527 -0.606281  0.319836 -0.210305  1.000000   
w -0.666213  0.391215  0.083154  0.150114 -0.619769 -0.215764 -0.430686   
x  0.036061  0.249027 -0.433272 -0.410009 -0.440047 -0.237842  0.308671   
y  0.113365 -0.049830 -0.013345 -0.297120 -0.114302 -0.184201  0.621780   

          w         x         y  
p -0.666213  0.036061  0.113365  
q  0.391215  0.249027 -0.049830  
r  0.083154 -0.433272 -0.013345  
s  0.150114 -0.410009 -0.297120  
t -0

p    0.77
q    0.64
r    0.21
s    0.85
t    0.62
u    0.02
v    0.62
w    0.39
x    0.24
y    0.14
dtype: float64

In [91]:
"""
Некоторые значения в столбце FlightNumber отсутствуют. Значения в столбце 
должны увеличиваться на 10 с каждой строкой, поэтому в пропусках необходимо
установить 10055 и 10075. Заполните эти недостающие числа и измените тип 
столбца с float на int
"""

def solution(df):
    df = 0# преобразуйте датафрейм в соответствии с условием 
    return df


df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

df["FlightNumber"].fillna(df['FlightNumber'].ffill()+10).astype(int)

# or

df["FlightNumber"] = df["FlightNumber"].interpolate().astype(int)

# or

In [92]:
def solution(df):
    df.FlightNumber = df.FlightNumber.interpolate(method='linear').astype(int)
    return df

In [93]:
def solution(df):
    df['FlightNumber'] = df['FlightNumber'].fillna((df['FlightNumber']\
            .shift(1) + df['FlightNumber'].shift(-1)) / 2).astype('int')
    return df

In [94]:
def solution(df):
    df['FlightNumber'] = df['FlightNumber'].\
          interpolate(method='linear',limit=10085,order=10)\
          .apply(lambda x: int(x))
    return df

In [95]:
def solution(df):
    df.FlightNumber = (df['FlightNumber'].fillna(method='ffill')\
                + df['FlightNumber'].fillna(method='backfill')) / 2
    df.FlightNumber = df.FlightNumber.astype(int)
    return df

In [114]:
df["From_To"].apply(lambda x: x.split("_")[0].lower().title())

0      London
1      Madrid
2      London
3    Budapest
4    Brussels
Name: From_To, dtype: object

In [111]:
# Разбейте данные из столбца From_To на два столбца From и То. 
# Исходный столбец удалите.

def solution(df):
    df["From"] = df["From_To"].apply(lambda x: x.split("_")[0].lower().title())
    df["To"] = df["From_To"].apply(lambda x: x.split("_")[1].lower().title())
    df = df.drop("From_To", axis=1)
    return df

df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

solution(df)

FlightNumber  RecentDelays              Airline      From         To
0       10045.0      [23, 47]               KLM(!)    LoNDon      paris
1           NaN            []    <Air France> (12)    MAdrid      miLAN
2       10065.0  [24, 43, 87]  (British Airways. )    londON  StockhOlm
3           NaN          [13]       12. Air France  Budapest      PaRis
4       10085.0      [67, 32]          "Swiss Air"  Brussels     londOn

In [120]:
def solution(df):
    temp = df.From_To.str.split('_')
    df['From'] = temp.str[0].str.title()
    df['To'] = temp.str[1].str.title()
    df.drop(['From_To'], axis=1, inplace=True)
    return df

In [ ]:
def solution(df):
    new_df = df.From_To.str.split('_', expand=True).apply(lambda x: x.str.title())
    new_df.columns = ['From', 'To']
    return df.iloc[:, 1:].join(new_df)

In [170]:
"""
В столбце Airline содержатся наименования авиакомпаний. Можно заметить, 
что в названиях присутствуют 'лишние' символы. Выполните преобразование 
столбца Airline:
"""
import re


def solution(df):
    df["Airline"] = df["Airline"].apply(lambda x: re.sub(r"[\W0-9]+"," ", x.strip())).apply(lambda x: x.strip())
    return df

df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
solution(df)

From_To  FlightNumber  RecentDelays          Airline
0      LoNDon_paris       10045.0      [23, 47]              KLM
1      MAdrid_miLAN           NaN            []       Air France
2  londON_StockhOlm       10065.0  [24, 43, 87]  British Airways
3    Budapest_PaRis           NaN          [13]       Air France
4   Brussels_londOn       10085.0      [67, 32]        Swiss Air

In [16]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

def solution(df):
    df.Airline = df.Airline.str.extract(r'([a-zA-Z]+[ ]*[a-zA-Z]+)')
    return df

solution(df)

From_To  FlightNumber  RecentDelays          Airline
0      LoNDon_paris       10045.0      [23, 47]              KLM
1      MAdrid_miLAN           NaN            []       Air France
2  londON_StockhOlm       10065.0  [24, 43, 87]  British Airways
3    Budapest_PaRis           NaN          [13]       Air France
4   Brussels_londOn       10085.0      [67, 32]        Swiss Air

In [177]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

def solution(df):
    df["Airline"] = df["Airline"].apply(lambda x: x.strip('! )"( 1 2 < > .'))
    return df

solution(df)

From_To  FlightNumber  RecentDelays          Airline
0      LoNDon_paris       10045.0      [23, 47]              KLM
1      MAdrid_miLAN           NaN            []       Air France
2  londON_StockhOlm       10065.0  [24, 43, 87]  British Airways
3    Budapest_PaRis           NaN          [13]       Air France
4   Brussels_londOn       10085.0      [67, 32]        Swiss Air

In [79]:
# Распакуйте данные из RecentDelays по столбцам delay_1 ... delay_n. 
# После распаковки удалите столбец RecentDelays.

df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
print(df)

def solution(df):
    RecentDelays = df["RecentDelays"].to_list()
    max_length_rd = max((len(i) for i in RecentDelays))
    RecentDelays = pd.DataFrame(RecentDelays, columns = ["delay_"+str(i+1) for i in range(max_length_rd)])
    df = pd.concat([df.drop("RecentDelays", axis=1), RecentDelays], axis=1)
    return df

solution(df)

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"


From_To  FlightNumber              Airline  delay_1  delay_2  \
0      LoNDon_paris       10045.0               KLM(!)     23.0     47.0   
1      MAdrid_miLAN           NaN    <Air France> (12)      NaN      NaN   
2  londON_StockhOlm       10065.0  (British Airways. )     24.0     43.0   
3    Budapest_PaRis           NaN       12. Air France     13.0      NaN   
4   Brussels_londOn       10085.0          "Swiss Air"     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN

In [80]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

def solution(df):
    new_df = df.RecentDelays.apply(pd.Series)
    new_df.columns = ['delay_1', 'delay_2', 'delay_3']
    return df.drop('RecentDelays', axis=1).join(new_df)

solution(df)

From_To  FlightNumber              Airline  delay_1  delay_2  \
0      LoNDon_paris       10045.0               KLM(!)     23.0     47.0   
1      MAdrid_miLAN           NaN    <Air France> (12)      NaN      NaN   
2  londON_StockhOlm       10065.0  (British Airways. )     24.0     43.0   
3    Budapest_PaRis           NaN       12. Air France     13.0      NaN   
4   Brussels_londOn       10085.0          "Swiss Air"     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN

In [81]:
df.RecentDelays.apply(pd.Series)

0     1     2
0  23.0  47.0   NaN
1   NaN   NaN   NaN
2  24.0  43.0  87.0
3  13.0   NaN   NaN
4  67.0  32.0   NaN